//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 

namespace ClearwaveMirthDemo { 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DefaultAcceptMessagePortBinding", Namespace="http://ws.connectors.connect.mirth.com/")]
    public partial class ClearwaveMirthService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback acceptMessageOperationCompleted;
    
        /// <remarks/>
        public ClearwaveMirthService() {
        }
    
        /// <remarks/>
        public event acceptMessageCompletedEventHandler acceptMessageCompleted;
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.connectors.connect.mirth.com/", ResponseNamespace="http://ws.connectors.connect.mirth.com/", Use=System.Web.Services.Description.SoapBindingUse.Encoded, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acceptMessage([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("acceptMessage", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginacceptMessage(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("acceptMessage", new object[] {
                        arg0}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndacceptMessage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public void acceptMessageAsync(string arg0) {
            this.acceptMessageAsync(arg0, null);
        }
    
        /// <remarks/>
        public void acceptMessageAsync(string arg0, object userState) {
            if ((this.acceptMessageOperationCompleted == null)) {
                this.acceptMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacceptMessageOperationCompleted);
            }
            this.InvokeAsync("acceptMessage", new object[] {
                        arg0}, this.acceptMessageOperationCompleted, userState);
        }
    
        private void OnacceptMessageOperationCompleted(object arg) {
            if ((this.acceptMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acceptMessageCompleted(this, new acceptMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void acceptMessageCompletedEventHandler(object sender, acceptMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class acceptMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal acceptMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
    
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}